"""Core MOBRA calculation, validation, I/O, and reporting utilities."""

from .acceptance import (
    ACCEPTANCE_DISPOSITIONS,
    MISSING_RESIDUAL_POLICIES,
    RISK_ACCEPTANCE_LIMITATION,
    RiskAcceptancePolicy,
    acceptance_status_counts,
    apply_risk_acceptance,
    risk_acceptance_summary,
    risk_acceptance_summary_table,
    risk_source_summary,
)
from .config import (
    APP_TITLE,
    APP_VERSION,
    AUTHOR_EMAIL,
    AUTHOR_NAME,
    FULL_DISCLAIMER,
    NORMATIVE_EVIDENCE_WORDING,
    configured_author_email,
)
from .critical_controls import (
    CONTROL_OUTCOMES,
    CRITICAL_CONTROL_LIMITATION,
    CRITICALITY_LEVELS,
    FAILURE_DISPOSITIONS,
    INCOMPLETE_RECORD_DISPOSITIONS,
    PROFILE_REQUIRED_COLUMNS,
    CriticalControlAssessment,
    CriticalControlProfileValidationResult,
    assess_critical_controls,
    critical_control_summary_table,
    validate_critical_control_profile,
)
from .decisions import DeploymentPolicy, deployment_decision
from .export_contracts import EXCEL_SHEETS, EXPORT_FILENAMES
from .mapping import (
    ALLOWED_CONTROL_ROLES,
    ALLOWED_RELATIONSHIP_TYPES,
    MAPPING_REQUIRED_COLUMNS,
    MappingValidationResult,
    get_hazards_for_requirement,
    get_requirements_for_hazard,
    hazards_without_requirements,
    mapping_coverage_summary,
    requirements_without_hazards,
    validate_mapping,
)
from .operational_tools import (
    MAX_EMAIL_ATTACHMENT_BYTES,
    EmailConfig,
    attachment_size_ok,
    build_backup_zip,
    build_field_assessment_package,
    build_hazard_import_template,
    build_hazard_pdf,
    build_hazard_register_workbook,
    build_orl_assessment_workbook,
    build_orl_pdf,
    build_requirements_import_template,
    reset_assessment_state,
    send_email_backup,
    valid_email,
)
from .readiness import calculate_bri, domain_readiness, failed_critical_controls
from .resources import (
    catalogue_csv_bytes,
    catalogue_xlsx_bytes,
    load_normative_resources,
    load_supporting_literature,
    validate_resource_manifest,
)
from .risk import (
    RISK_CATEGORIES,
    RISK_COLORS,
    RISK_LEVELS,
    classify_risk,
    heatmap_counts,
    heatmap_total,
)
from .validation import ValidationResult, validate_hazards, validate_requirements
from .validation_exports import invalid_records_workbook_bytes, validation_json_fields
from .validation_findings import (
    VALIDATION_FINDING_CODES,
    VALIDATION_LIMITATION,
    CrossDatasetValidationResult,
    ValidationFinding,
    findings_frame,
    validate_cross_dataset_consistency,
    validation_summary,
)

__all__ = [
    "ACCEPTANCE_DISPOSITIONS",
    "APP_TITLE",
    "APP_VERSION",
    "AUTHOR_EMAIL",
    "AUTHOR_NAME",
    "configured_author_email",
    "CONTROL_OUTCOMES",
    "CRITICALITY_LEVELS",
    "CRITICAL_CONTROL_LIMITATION",
    "CriticalControlAssessment",
    "CriticalControlProfileValidationResult",
    "EmailConfig",
    "DeploymentPolicy",
    "EXCEL_SHEETS",
    "EXPORT_FILENAMES",
    "FAILURE_DISPOSITIONS",
    "FULL_DISCLAIMER",
    "INCOMPLETE_RECORD_DISPOSITIONS",
    "MISSING_RESIDUAL_POLICIES",
    "PROFILE_REQUIRED_COLUMNS",
    "ALLOWED_CONTROL_ROLES",
    "ALLOWED_RELATIONSHIP_TYPES",
    "MAPPING_REQUIRED_COLUMNS",
    "MAX_EMAIL_ATTACHMENT_BYTES",
    "MappingValidationResult",
    "RISK_CATEGORIES",
    "RISK_COLORS",
    "RISK_LEVELS",
    "RISK_ACCEPTANCE_LIMITATION",
    "RiskAcceptancePolicy",
    "NORMATIVE_EVIDENCE_WORDING",
    "ValidationResult",
    "ValidationFinding",
    "CrossDatasetValidationResult",
    "VALIDATION_LIMITATION",
    "VALIDATION_FINDING_CODES",
    "calculate_bri",
    "assess_critical_controls",
    "classify_risk",
    "critical_control_summary_table",
    "acceptance_status_counts",
    "apply_risk_acceptance",
    "deployment_decision",
    "domain_readiness",
    "failed_critical_controls",
    "get_hazards_for_requirement",
    "get_requirements_for_hazard",
    "hazards_without_requirements",
    "heatmap_counts",
    "heatmap_total",
    "mapping_coverage_summary",
    "risk_acceptance_summary",
    "risk_acceptance_summary_table",
    "risk_source_summary",
    "requirements_without_hazards",
    "validate_hazards",
    "validate_critical_control_profile",
    "validate_mapping",
    "validate_requirements",
    "validate_cross_dataset_consistency",
    "validation_summary",
    "validation_json_fields",
    "findings_frame",
    "invalid_records_workbook_bytes",
    "attachment_size_ok",
    "build_backup_zip",
    "build_field_assessment_package",
    "build_hazard_import_template",
    "build_hazard_pdf",
    "build_hazard_register_workbook",
    "build_orl_assessment_workbook",
    "build_orl_pdf",
    "build_requirements_import_template",
    "catalogue_csv_bytes",
    "catalogue_xlsx_bytes",
    "load_normative_resources",
    "load_supporting_literature",
    "reset_assessment_state",
    "send_email_backup",
    "valid_email",
    "validate_resource_manifest",
]
